# Logging Configuration
logging.level.org.springframework=debug
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

# Database Configuration
spring.datasource.url=jdbc:sqlite:securitydb.sqlite
spring.datasource.driver-class-name=org.sqlite.JDBC

com.softlines.fastpos.security.driver-class-name=org.sqlite.JDBC
com.softlines.fastpos.security.db.name=jwtauthsoftlines
com.softlines.fastpos.security.db.port=3366
com.softlines.fastpos.security.url=jdbc:sqlite:securitydb.sqlite
com.softlines.fastpos.security.username=root
com.softlines.fastpos.security.password=


# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.properties.hibernate.format_sql=true
hibernate.hbm2ddl.auto=update
hibernate.show-sql=true

# Hibernate DDL and SQL Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=always

# Spring Boot Specific Configurations
spring.devtools.livereload.enabled=true
spring.main.allow-bean-definition-overriding=true
spring.messages.basename=messages


spring.main.allow-circular-references=true

# Server Port
#server.port=8080
server.port=8080