logging.level.org.springframework =debug
com.softlines.fastpos.security.db.name=jwtauthsoftlines
com.softlines.fastpos.security.db.port=3306
com.softlines.fastpos.security.url=jdbc:mysql://localhost:3306/securitydb?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
spring.datasource.sqlScriptEncoding=UTF-8
com.softlines.fastpos.security.username=root
com.softlines.fastpos.security.password=
#management.endpoint.health.show-details=always
hibernate.hbm2ddl.auto=update
hibernate.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

spring.devtools.livereload.enabled=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQL5Dialect

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect

spring.jpa.properties.hibernate.dialect.storage_engine=innodb
#hibernate.generate_statistics=true
spring.main.allow-bean-definition-overriding=true
spring.messages.basename=messages
spring.profiles.active=dev

server.port=8080